# Generated by Django 3.2 on 2021-07-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JewleryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('is_womanly', models.BooleanField(default=True)),
                ('is_unisex', models.BooleanField(default=False)),
                ('is_used', models.BooleanField(default=False)),
                ('is_domestic', models.BooleanField(default=True)),
                ('made_in', models.CharField(blank=True, max_length=264, null=True)),
                ('weight', models.IntegerField()),
                ('company_name', models.CharField(blank=True, max_length=264, null=True)),
                ('karat', models.IntegerField(default=750)),
                ('is_available', models.BooleanField(default=True)),
                ('buy_wage', models.IntegerField()),
                ('sale_wage', models.IntegerField()),
                ('wholesale_wage', models.IntegerField()),
                ('is_goldset', models.BooleanField(default=False)),
                ('is_pendant', models.BooleanField(default=False)),
                ('is_bracelet', models.BooleanField(default=False)),
                ('is_necklace', models.BooleanField(default=False)),
                ('is_bangle', models.BooleanField(default=False)),
                ('is_chain', models.BooleanField(default=False)),
                ('is_earings', models.BooleanField(default=False)),
                ('is_halfset', models.BooleanField(default=False)),
                ('is_watch', models.BooleanField(default=False)),
                ('is_anklet', models.BooleanField(default=False)),
            ],
        ),
    ]
