# Generated by Django 3.2 on 2021-07-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewlery', '0002_jewlerypicturemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewlerymodel',
            name='is_confirmed',
            field=models.BooleanField(default=True),
        ),
    ]
