# Generated by Django 3.2 on 2021-08-09 08:30

import datetime
from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('jewlery', '0006_alter_unitmodel_jdatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitmodel',
            name='jdatetime',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2021, 8, 9, 13, 0, 16, 58285)),
        ),
    ]
