# Generated by Django 3.2 on 2021-08-11 11:21

import datetime
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('jewlery', '0007_alter_unitmodel_jdatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewlerymodel',
            name='buy_wage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='jewlerymodel',
            name='sale_wage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='jewlerymodel',
            name='weight',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='jewlerymodel',
            name='wholesale_wage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='unitmodel',
            name='jdatetime',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2021, 8, 11, 15, 51, 27, 550504)),
        ),
    ]
