# Generated by Django 3.2 on 2021-08-12 11:05

import datetime
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('jewlery', '0008_auto_20210811_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewlerymodel',
            name='instance_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unitmodel',
            name='jdatetime',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2021, 8, 12, 15, 35, 37, 302835)),
        ),
    ]
