# Generated by Django 3.2 on 2021-08-12 12:00

import datetime
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('jewlery', '0009_auto_20210812_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitmodel',
            name='last_jewlery_update',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name='unitmodel',
            name='jdatetime',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2021, 8, 12, 16, 30, 42, 117071)),
        ),
    ]
