# Generated by Django 3.2 on 2021-08-12 14:45

import datetime
from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('jewlery', '0010_auto_20210812_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitmodel',
            name='jdatetime',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2021, 8, 12, 19, 15, 19, 921582)),
        ),
    ]
