# Generated by Django 3.2 on 2021-08-15 12:25

import datetime
from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('jewlery', '0011_alter_unitmodel_jdatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitmodel',
            name='jdatetime',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2021, 8, 15, 16, 55, 20, 775638)),
        ),
    ]
