# Generated by Django 3.2 on 2021-08-18 15:39

import datetime
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('jewlery', '0012_alter_unitmodel_jdatetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitmodel',
            name='auto_update',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='unitmodel',
            name='last_unit_update',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
        migrations.AddField(
            model_name='unitmodel',
            name='unit_gram',
            field=models.IntegerField(default=11200000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unitmodel',
            name='jdatetime',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2021, 8, 18, 20, 9, 6, 638172)),
        ),
    ]
