# Generated by Django 3.2 on 2021-10-23 09:48

import datetime
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('jewlery', '0014_auto_20210828_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewlerymodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unitmodel',
            name='jdatetime',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2021, 10, 23, 13, 18, 25, 953561)),
        ),
    ]
