# Generated by Django 3.2 on 2021-07-18 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commonuser', '0002_commonusermodel_is_jewler_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commonusermodel',
            old_name='is_jeweler',
            new_name='is_jewler',
        ),
    ]
