# Generated by Django 3.2 on 2021-07-25 10:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commonuser', '0003_rename_is_jeweler_commonusermodel_is_jewler'),
        ('jewlery', '0003_jewlerymodel_is_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_checked', models.BooleanField(default=False)),
                ('numbers', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('datetime', django_jalali.db.models.jDateTimeField(default=datetime.datetime(2021, 7, 25, 14, 37, 23, 634136))),
                ('check_datetime', django_jalali.db.models.jDateTimeField(blank=True, null=True)),
                ('commonuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='commonuser.commonusermodel')),
                ('jewlery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='jewlery.jewlerymodel')),
            ],
        ),
    ]
