# Generated by Django 3.2 on 2021-07-26 15:02

import datetime
from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='datetime',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2021, 7, 26, 19, 32, 56, 241029)),
        ),
    ]
