# Generated by Django 3.2 on 2021-08-01 09:44

import datetime
from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_ordermodel_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='datetime',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2021, 8, 1, 14, 14, 59, 127096)),
        ),
    ]
