# Generated by Django 3.2 on 2021-08-08 12:49

import datetime
from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_ordermodel_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='datetime',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='jdatetime',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2021, 8, 8, 17, 19, 0, 701820)),
        ),
    ]
