# Generated by Django 3.2 on 2021-08-11 11:21

import datetime
from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20210809_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='jdatetime',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2021, 8, 11, 15, 51, 27, 566127)),
        ),
    ]
