# Generated by Django 3.2 on 2021-08-12 11:05

import datetime
from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_ordermodel_jdatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='jdatetime',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2021, 8, 12, 15, 35, 37, 303834)),
        ),
    ]
