# Generated by Django 3.2 on 2021-08-12 12:00

import datetime
from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_ordermodel_jdatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='jdatetime',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2021, 8, 12, 16, 30, 42, 118070)),
        ),
    ]
