# Generated by Django 3.2 on 2021-08-18 15:39

import datetime
from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20210815_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='jdatetime',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2021, 8, 18, 20, 9, 6, 642332)),
        ),
    ]
